// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/chats": {
    params: {};
  };
  "/api/chat/message": {
    params: {};
  };
  "/api/promo-code": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/chats" | "/api/chat/message" | "/api/promo-code";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/api.chats.tsx": {
    id: "routes/api.chats";
    page: "/api/chats";
  };
  "./routes/api.chat.message.tsx": {
    id: "routes/api.chat.message";
    page: "/api/chat/message";
  };
  "./routes/api.promo-code.tsx": {
    id: "routes/api.promo-code";
    page: "/api/promo-code";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/api.chats": typeof import("./app/./routes/api.chats.tsx");
  "routes/api.chat.message": typeof import("./app/./routes/api.chat.message.tsx");
  "routes/api.promo-code": typeof import("./app/./routes/api.promo-code.tsx");
};